package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"
	"project1540-api/external/models"
	"project1540-api/graph/generated"
)

// Results is the resolver for the Results field.
func (r *aPIResponseResolver) Results(ctx context.Context, obj *models.APIResponse) ([]*models.Response, error) {
	panic(fmt.Errorf("not implemented: Results - Results"))
}

// Request is the resolver for the request field.
func (r *queryResolver) Request(ctx context.Context) (*models.Request, error) {
	panic(fmt.Errorf("not implemented: Request - request"))
}

// APIResponse returns generated.APIResponseResolver implementation.
func (r *Resolver) APIResponse() generated.APIResponseResolver { return &aPIResponseResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type aPIResponseResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
