// Code generated by MockGen. DO NOT EDIT.
// Source: facade.go

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	reflect "reflect"

	models "github.com/calebtracey/project1540-api/external/models"
	postgres "github.com/calebtracey/project1540-api/external/models/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockIFacade is a mock of IFacade interface.
type MockIFacade struct {
	ctrl     *gomock.Controller
	recorder *MockIFacadeMockRecorder
}

// MockIFacadeMockRecorder is the mock recorder for MockIFacade.
type MockIFacadeMockRecorder struct {
	mock *MockIFacade
}

// NewMockIFacade creates a new mock instance.
func NewMockIFacade(ctrl *gomock.Controller) *MockIFacade {
	mock := &MockIFacade{ctrl: ctrl}
	mock.recorder = &MockIFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFacade) EXPECT() *MockIFacadeMockRecorder {
	return m.recorder
}

// InsertNewFileDetails mocks base method.
func (m *MockIFacade) InsertNewFileDetails(ctx context.Context, fileName, fileType, url string, tags []string) *models.ErrorLog {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertNewFileDetails", ctx, fileName, fileType, url, tags)
	ret0, _ := ret[0].(*models.ErrorLog)
	return ret0
}

// InsertNewFileDetails indicates an expected call of InsertNewFileDetails.
func (mr *MockIFacadeMockRecorder) InsertNewFileDetails(ctx, fileName, fileType, url, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertNewFileDetails", reflect.TypeOf((*MockIFacade)(nil).InsertNewFileDetails), ctx, fileName, fileType, url, tags)
}

// SearchFilesByTag mocks base method.
func (m *MockIFacade) SearchFilesByTag(ctx context.Context, tags []string) postgres.FileResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFilesByTag", ctx, tags)
	ret0, _ := ret[0].(postgres.FileResponse)
	return ret0
}

// SearchFilesByTag indicates an expected call of SearchFilesByTag.
func (mr *MockIFacadeMockRecorder) SearchFilesByTag(ctx, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFilesByTag", reflect.TypeOf((*MockIFacade)(nil).SearchFilesByTag), ctx, tags)
}
